-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_logs
(
    id integer NOT NULL DEFAULT nextval('admin_logs_id_seq'::regclass),
    order_id integer NOT NULL,
    admin_comment text COLLATE pg_catalog."default",
    log_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL DEFAULT nextval('categories_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.history
(
    id integer NOT NULL DEFAULT nextval('history_id_seq'::regclass),
    medicine_id integer NOT NULL,
    quantity integer NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    purchase_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medicines
(
    id integer NOT NULL DEFAULT nextval('medicines_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    where_from text COLLATE pg_catalog."default" NOT NULL,
    expiration_date date NOT NULL,
    price numeric(10, 2) NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT medicines_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
    medicine_id integer NOT NULL,
    quantity integer NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    order_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    card_number character varying(16) COLLATE pg_catalog."default" NOT NULL,
    card_expiry date NOT NULL,
    cvv character varying(4) COLLATE pg_catalog."default" NOT NULL
);

ALTER TABLE IF EXISTS public.admin_logs
    ADD CONSTRAINT admin_logs_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.history
    ADD CONSTRAINT history_medicine_id_fkey FOREIGN KEY (medicine_id)
    REFERENCES public.medicines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.medicines
    ADD CONSTRAINT medicines_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_medicine_id_fkey FOREIGN KEY (medicine_id)
    REFERENCES public.medicines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;